/**
 * Broker catalogue, part 2 of 3 — see brokerCatalogPart1.ts for context.
 */

import type { BrokerInfo } from "./brokerCatalogTypes";

export const BROKERS_PART2: BrokerInfo[] = [
  {
    id: "flattrade",
    name: "Flattrade (Pi)",
    logo: "📉",
    color: "hsl(340 75% 55%)",
    description: "Live NSE/BSE index option-chain data via Flattrade's PiConnect API, using a daily instrument master and rate-limited per-contract quotes with Black-Scholes-derived Greeks.",
    docsUrl: "https://piconnect.flattrade.in/docs",
    features: ["Option Chain", "Live Quotes", "Index Spot LTP", "Expiry List"],
    fields: [
      { key: "clientId", label: "Client ID (UCC)", placeholder: "FZ00000", type: "text", required: true, helpText: "Your Flattrade trading account Client ID / UCC." },
      { key: "apiKey", label: "API Key", placeholder: "App API Key from wall.flattrade.in", type: "text", required: true, helpText: "From Flattrade Pi app registration at wall.flattrade.in → Pi → Create New API Key." },
      { key: "apiSecret", label: "API Secret", placeholder: "App API Secret", type: "password", required: true, helpText: "The secret paired with your API Key, revealed via the eye icon on wall.flattrade.in." },
      { key: "requestCode", label: "Request Code", placeholder: "One-time code from the login redirect", type: "password", required: true, helpText: "Visit https://auth.flattrade.in/?app_key=<your API Key>, log in, then copy the request_code from the redirect URL. Valid only a few minutes — paste and save immediately. Needed again whenever the daily session expires (Flattrade clears sessions 5-6 AM IST)." },
    ],
  },
  {
    id: "groww",
    name: "Groww",
    logo: "🌱",
    color: "hsl(150 60% 45%)",
    description: "Live NIFTY/BANKNIFTY/FINNIFTY/MIDCPNIFTY/SENSEX option chains via Groww's checksum-authenticated Trading API, with Black-Scholes-derived IV and Greeks.",
    docsUrl: "https://groww.in/trade-api/docs/curl",
    features: ["Option Chain", "Live Quotes", "Checksum Auth"],
    fields: [
      { key: "apiKey", label: "API Key", placeholder: "Enter Groww API Key", type: "text", required: true, helpText: "From Groww app → Profile → Trading APIs → Generate API keys" },
      { key: "apiSecret", label: "API Secret", placeholder: "Enter Groww API Secret", type: "password", required: true, helpText: "Shown once when the API key is generated; requires daily approval in the Groww app" },
    ],
  },
  {
    id: "hdfcsecurities",
    name: "HDFC Securities (InvestRight)",
    logo: "🏦",
    color: "hsl(0 70% 45%)",
    description: "Live NIFTY/BANKNIFTY/FINNIFTY/MIDCPNIFTY/SENSEX option-chain data via HDFC Securities' InvestRight API — REST LTP plus a persistent WebSocket feed for OI, volume and depth.",
    docsUrl: "https://developer.hdfcsec.com",
    features: ["Option Chain", "Live Quotes", "Open Interest", "Market Depth"],
    fields: [
      { key: "apiKey", label: "API Key", placeholder: "Your InvestRight app API key", type: "text", required: true, helpText: "From your InvestRight developer app registration. Sent as an api_key query param on every request." },
      { key: "accessToken", label: "Access Token", placeholder: "Paste the accessToken from InvestRight login", type: "password", required: true, helpText: "InvestRight's login is a browser-redirect OAuth flow. Complete it once (GET /oapi/v1/login, then exchange the returned request_token for an accessToken using your apiSecret), then paste the resulting accessToken here. Valid for the rest of the trading day — re-paste if calls start failing with a session-expired error." },
    ],
  },
  {
    id: "hdfcsky",
    name: "HDFC Sky (HDFC Securities)",
    logo: "☁️",
    color: "hsl(205 75% 50%)",
    description: "Live NIFTY/BANKNIFTY/FINNIFTY/MIDCPNIFTY/SENSEX option chain via HDFC Sky's Open API, with IV/Greeks computed via Black-Scholes from real traded LTP.",
    docsUrl: "https://developer.hdfcsky.com/sky-docs/docs/intro",
    features: ["Option Chain", "Live LTP", "Expiry List", "Black-Scholes Greeks"],
    fields: [
      { key: "apiKey", label: "API Key", placeholder: "e.g. f700ed935c074eab83f177d8...", type: "text", required: true, helpText: "From HDFC Sky's developer portal (developer.hdfcsky.com). Sent as the api_key query param on every call." },
      { key: "accessToken", label: "Access Token", placeholder: "Paste the accessToken JWT from the login flow", type: "password", required: true, helpText: "Complete HDFC Sky's login flow (browser redirect: GET /oapi/v1/login -> HDFC login/OTP/PIN -> POST /oapi/v1/access-token) once externally and paste the resulting accessToken here. Sent as a raw Authorization header (no 'Bearer ' prefix). Re-paste when it expires." },
    ],
  },
  {
    id: "ibulls",
    name: "IndiaBulls Securities (XTS Market Data)",
    logo: "🐂",
    color: "hsl(15 80% 50%)",
    description: "Live NIFTY/BANKNIFTY/FINNIFTY/MIDCPNIFTY/SENSEX option chains from IndiaBulls Securities' XTS market-data API, with instrument-master-driven strike/expiry resolution and Black-Scholes-filled Greeks.",
    docsUrl: "https://symphonyfintech.com/xts-trading-front-end-api/",
    features: ["Option Chain", "Live Quotes", "Open Interest", "Expiry List"],
    fields: [
      { key: "marketApiKey", label: "Market Data API Key", placeholder: "appKey from IndiaBulls XTS developer portal", type: "password", required: true, helpText: "The 'Market Data API' appKey — distinct from the 'Interactive API' key used for order placement, which this integration never needs." },
      { key: "marketApiSecret", label: "Market Data API Secret", placeholder: "secretKey from IndiaBulls XTS developer portal", type: "password", required: true, helpText: "The 'Market Data API' secretKey, paired with the appKey above." },
    ],
  },
  {
    id: "iifl",
    name: "IIFL Securities",
    logo: "🔷",
    color: "hsl(230 65% 50%)",
    description: "Live NIFTY/BANKNIFTY/FINNIFTY/MIDCPNIFTY/SENSEX option chains via IIFL's XTS Market Data API — daily instrument master + batched quotes, Black-Scholes IV/Greeks fill-in.",
    docsUrl: "https://ttblaze.iifl.com",
    features: ["Option Chain", "Live Quotes", "Open Interest", "IV & Greeks"],
    fields: [
      { key: "apiKey", label: "Market Data App Key", placeholder: "App key from IIFL's Market Data API app", type: "text", required: true, helpText: "From your IIFL Securities developer account — the App Key for the Market Data API app (a separate app registration from the Interactive/trading API; this integration is read-only and never uses the Interactive app's credentials)." },
      { key: "apiSecret", label: "Market Data Secret Key", placeholder: "Secret key from IIFL's Market Data API app", type: "password", required: true, helpText: "The matching Secret Key for the Market Data App Key above." },
    ],
  },
  {
    id: "iiflcapital",
    name: "IIFL Capital",
    logo: "🔶",
    color: "hsl(25 85% 50%)",
    description: "Live NIFTY/BANKNIFTY/FINNIFTY/MIDCPNIFTY/SENSEX option chains via IIFL Capital's REST API, built from its daily contract-master CSVs plus batched market-quote and per-leg open-interest calls.",
    docsUrl: "https://api.iiflcapital.com/",
    features: ["Option Chain", "Live Quotes", "Open Interest", "Black-Scholes Greeks"],
    fields: [
      { key: "clientId", label: "Client ID", placeholder: "e.g. AB1234", type: "text", required: true, helpText: "Your IIFL Capital client ID — also returned as the `clientId` query param when IIFL redirects you back after logging in." },
      { key: "appSecret", label: "App Secret", placeholder: "App secret from your Relationship Manager", type: "password", required: true, helpText: "App Secret for your registered API application — obtained from your IIFL Relationship Manager / Point of Contact, not from the login page." },
      { key: "authCode", label: "Auth Code (daily)", placeholder: "Paste today's authCode", type: "password", required: true, helpText: "Single-use code from today's login: visit https://markets.iiflcapital.com/?v=1&appkey=YOUR_APP_KEY&redirecturl=YOUR_URL, log in with your trading credentials + OTP/TOTP, and copy the `authCode` IIFL redirects you back with. Must be regenerated once per trading day." },
    ],
  },
  {
    id: "indmoney",
    name: "IndMoney (INDstocks)",
    logo: "💰",
    color: "hsl(140 65% 42%)",
    description: "Live NIFTY/BANKNIFTY/FINNIFTY/MIDCPNIFTY/SENSEX option-chain data via INDstocks' instrument master + batched quotes, with Black-Scholes-derived IV and Greeks.",
    docsUrl: "https://api-docs.indstocks.com/",
    features: ["Option Chain", "Live Quotes", "Multi-Index", "TOTP Login"],
    fields: [
      { key: "accessToken", label: "Access Token (optional if using MPIN + TOTP)", placeholder: "Paste your 24-hour INDstocks access token", type: "password", required: false, helpText: "Generate at indstocks.com -> API Trading -> Generate Token. Valid 24 hours. Leave blank to use MPIN + TOTP login instead." },
      { key: "clientId", label: "Client ID", placeholder: "e.g. IND1234567", type: "text", required: false, helpText: "Shown on the INDstocks access-tokens page after TOTP setup. Required only for MPIN + TOTP login (sent as the x-api-key header)." },
      { key: "mpin", label: "MPIN", placeholder: "Your INDstocks account MPIN", type: "password", required: false, helpText: "Required only for MPIN + TOTP login." },
      { key: "totpSecret", label: "TOTP Secret", placeholder: "Base32 secret from your authenticator app setup", type: "password", required: false, helpText: "Required only for MPIN + TOTP login. The base32 secret key (not a 6-digit code) — used to generate a fresh code each session." },
    ],
  },
  {
    id: "jainamxts",
    name: "Jainam (XTS)",
    logo: "⚡",
    color: "hsl(50 90% 50%)",
    description: "Live NIFTY/BANKNIFTY/FINNIFTY/MIDCPNIFTY/SENSEX option chain data via Jainam's Symphony Fintech XTS market-data API, with Black-Scholes IV/Greeks fill-in.",
    docsUrl: "https://developers.symphonyfintech.in/doc/marketdata/",
    features: ["Option Chain", "Live LTP", "Open Interest", "Expiry List", "Black-Scholes Greeks"],
    fields: [
      { key: "apiKey", label: "Market Data API Key", placeholder: "Enter your Jainam XTS Market Data API Key", type: "text", required: true, helpText: "Raise a Symphony API activation ticket with Jainam support (client name, mobile, email, client code, branch code) to get this — it is the Market Data appKey, separate from the Interactive/order-placement key." },
      { key: "apiSecret", label: "Market Data API Secret", placeholder: "Enter your Jainam XTS Market Data API Secret", type: "password", required: true, helpText: "Issued alongside the Market Data API Key by Jainam support." },
    ],
  },
  {
    id: "kotak",
    name: "Kotak Securities (Neo)",
    logo: "🔴",
    color: "hsl(355 75% 48%)",
    description: "Live NIFTY/BANKNIFTY/FINNIFTY/MIDCPNIFTY/SENSEX option chains via Kotak Neo's TOTP+MPIN session, daily scrip-master CSV, and batched neosymbol quotes.",
    docsUrl: "https://github.com/marketcalls/broker-api-docs/tree/main/kotak-api-docs",
    features: ["Option Chain", "Live Quotes", "TOTP Login", "Daily Scrip Master", "IV/Greeks (Black-Scholes)"],
    fields: [
      { key: "accessToken", label: "Neo API Access Token", placeholder: "eyJhbGciOi...", type: "password", required: true, helpText: "Neo app > More > Trade API > Your Applications. Identifies your registered API app; also used directly (not the session token) for all read-only market-data calls." },
      { key: "mobileNumber", label: "Registered Mobile Number", placeholder: "+919876543210", type: "text", required: true, helpText: "The mobile number registered with your Kotak trading account." },
      { key: "ucc", label: "UCC (Client Code)", placeholder: "ABC123", type: "text", required: true, helpText: "Your Unique Client Code / Client ID." },
      { key: "totpSecret", label: "TOTP Secret", placeholder: "JBSWY3DPEHPK3PXP", type: "password", required: true, helpText: "The base32 secret from the QR code shown during Kotak Neo's one-time 'TOTP Registration' step in the API dashboard (not a live 6-digit code)." },
      { key: "mpin", label: "Trading MPIN", placeholder: "123456", type: "password", required: true, helpText: "Your 6-digit Kotak Neo trading MPIN." },
    ],
  },
  {
    id: "motilal",
    name: "Motilal Oswal",
    logo: "🔵",
    color: "hsl(220 70% 50%)",
    description: "Active-login (SHA-256 + TOTP) integration building the option chain from Motilal's public CSV instrument masters plus per-strike LTP calls, with Black-Scholes IV/Greeks fill-in.",
    docsUrl: "https://openapi.motilaloswal.com",
    features: ["Option Chain", "Live LTP", "Bid/Ask", "Greeks (computed)"],
    fields: [
      { key: "apiKey", label: "App API Key", placeholder: "Enter your Motilal Oswal App API Key", type: "text", required: true, helpText: "From Motilal Oswal's developer/API portal — also hashed into the login password" },
      { key: "apiSecret", label: "App API Secret", placeholder: "Enter your Motilal Oswal App API Secret (optional)", type: "password", required: false, helpText: "Optional — enables the extra getaccesstoken step; login still works without it" },
      { key: "clientId", label: "Client User ID", placeholder: "Enter your Motilal Oswal Client / User ID", type: "text", required: true, helpText: "Your trading login ID" },
      { key: "password", label: "Trading Password", placeholder: "Enter your trading password", type: "password", required: true, helpText: "Hashed with your API Key before being sent — never stored in plaintext by the broker" },
      { key: "dob", label: "Date of Birth (2FA)", placeholder: "DD/MM/YYYY", type: "text", required: true, helpText: "Used as the account's 2FA value during login, e.g. 18/10/1988" },
      { key: "totpSecret", label: "TOTP Secret", placeholder: "Enter TOTP secret (base32) from your authenticator app setup", type: "password", required: true, helpText: "Base32 secret used to auto-generate a fresh 6-digit TOTP code on every login — Motilal's own SMS/Email OTP flow is not supported" },
    ],
  },
];
