/**
 * Broker catalogue, part 1 of 3 (alphabetical-by-position slice of the original
 * 496-line brokerCatalog.ts, split to respect the 300-line file limit). Pure
 * data — no behaviour. See brokerCatalog.ts for the merged BROKERS export.
 */

import type { BrokerInfo } from "./brokerCatalogTypes";

export const BROKERS_PART1: BrokerInfo[] = [
  {
    id: "dhan",
    name: "Dhan",
    logo: "🟢",
    color: "hsl(142 71% 45%)",
    description: "Lightning-fast trading with real-time option chain, Greeks, and OI data via Dhan API v2.",
    docsUrl: "https://dhanhq.co/docs/v2/",
    features: ["Option Chain", "Live LTP", "Greeks", "OI Data", "Expiry List"],
    fields: [
      { key: "clientId", label: "Client ID", placeholder: "Enter your Dhan Client ID", type: "text", required: true, helpText: "Found in Dhan Developer Console → API Management" },
      { key: "accessToken", label: "Access Token", placeholder: "Enter your Dhan Access Token", type: "password", required: true, helpText: "Generate from Dhan Developer Console → Create Token" },
    ],
  },
  {
    id: "zerodha",
    name: "Zerodha (Kite)",
    logo: "🔴",
    color: "hsl(0 84% 60%)",
    description: "India's largest broker. Access live data via Kite Connect API (REST polling).",
    docsUrl: "https://kite.trade/docs/connect/v3/",
    features: ["Option Chain", "Live Quotes", "Historical Data"],
    fields: [
      { key: "apiKey", label: "API Key", placeholder: "Enter Kite Connect API Key", type: "text", required: true, helpText: "From Kite Developer Console → My Apps" },
      { key: "apiSecret", label: "API Secret", placeholder: "Enter Kite Connect API Secret", type: "password", required: true, helpText: "From Kite Developer Console → My Apps" },
      { key: "accessToken", label: "Access Token", placeholder: "Enter session Access Token", type: "password", required: true, helpText: "Generated after login flow via /session/token" },
    ],
  },
  {
    id: "angelone",
    name: "Angel One (SmartAPI)",
    logo: "🟠",
    color: "hsl(25 95% 53%)",
    description: "Full-featured SmartAPI with option chain, order placement, and portfolio tracking.",
    docsUrl: "https://smartapi.angelone.in/docs",
    features: ["Option Chain", "Live Quotes", "Order Placement", "Portfolio"],
    fields: [
      { key: "apiKey", label: "API Key", placeholder: "Enter SmartAPI Key", type: "text", required: true, helpText: "From SmartAPI Portal → My Apps" },
      { key: "clientId", label: "Client ID", placeholder: "Enter Angel One Client ID", type: "text", required: true },
      { key: "password", label: "Password / MPIN", placeholder: "Enter login password or MPIN", type: "password", required: true },
      { key: "totpSecret", label: "TOTP Secret", placeholder: "Enter TOTP secret for 2FA", type: "password", required: true, helpText: "Base32 secret from Angel One's TOTP setup — required for automated daily login (sessions expire at midnight IST)" },
    ],
  },
  {
    id: "upstox",
    name: "Upstox",
    logo: "🟣",
    color: "hsl(271 76% 53%)",
    description: "Upstox API v2 with market data, option chain, and advanced order types.",
    docsUrl: "https://upstox.com/developer/api-documentation/",
    features: ["Option Chain", "Market Data", "Orders", "Portfolio"],
    fields: [
      { key: "apiKey", label: "API Key", placeholder: "Enter Upstox API Key", type: "text", required: true, helpText: "From Upstox Developer Console" },
      { key: "apiSecret", label: "API Secret", placeholder: "Enter Upstox API Secret", type: "password", required: true },
      { key: "accessToken", label: "Access Token", placeholder: "Enter OAuth Access Token", type: "password", required: true, helpText: "Generated via OAuth2 redirect flow" },
    ],
  },
  {
    id: "fivepaisa",
    name: "5paisa",
    logo: "🔵",
    color: "hsl(217 91% 60%)",
    description: "5paisa Connect API for live market data, option chain, and trading.",
    docsUrl: "https://www.5paisa.com/developerapi/overview",
    features: ["Option Chain", "Market Data", "Orders"],
    fields: [
      { key: "appName", label: "App Name", placeholder: "Enter 5paisa App Name", type: "text", required: true, helpText: "From 5paisa Developer Portal → My Apps" },
      { key: "appSource", label: "App Source", placeholder: "Enter App Source ID", type: "text", required: true },
      { key: "userKey", label: "User Key (App Key)", placeholder: "Enter your app's User Key", type: "password", required: true, helpText: "Sent as head.Key on every API call — from Developer Portal → My Apps" },
      { key: "encryptionKey", label: "Encryption Key", placeholder: "Enter Encryption Key", type: "password", required: true, helpText: "Client-specific — from your 5paisa account API settings" },
      { key: "userId", label: "User ID", placeholder: "Enter User ID", type: "text", required: true },
      { key: "clientCode", label: "Client Code / Email", placeholder: "Enter Client Code or login Email", type: "text", required: true, helpText: "Your own 5paisa login identifier (not the app's)" },
      { key: "pin", label: "PIN", placeholder: "Enter 4-digit login PIN", type: "password", required: true },
      { key: "totpSecret", label: "TOTP Secret", placeholder: "Enter TOTP secret for daily login", type: "password", required: true, helpText: "Base32 secret from 5paisa's TOTP setup — used to auto-login each trading day (token expires 11:59 PM IST daily)" },
    ],
  },
  {
    id: "fyers",
    name: "Fyers",
    logo: "🟡",
    color: "hsl(48 96% 53%)",
    description: "Fyers API v3 with TradingView charting, market data, and algo trading support.",
    docsUrl: "https://myapi.fyers.in/docs/",
    features: ["Option Chain", "Historical Data", "TradingView Charts", "Orders"],
    fields: [
      { key: "appId", label: "App ID", placeholder: "Enter Fyers App ID", type: "text", required: true, helpText: "Format: XXXX-100 from Fyers API Dashboard" },
      { key: "secretKey", label: "Secret Key", placeholder: "Enter Fyers Secret Key", type: "password", required: true },
      { key: "accessToken", label: "Access Token", placeholder: "Enter Fyers Access Token", type: "password", required: true },
    ],
  },
  {
    id: "aliceblue",
    name: "Alice Blue",
    logo: "💎",
    color: "hsl(199 89% 48%)",
    description: "Alice Blue ANT API for low-cost trading with real-time market feeds.",
    docsUrl: "https://v2api.aliceblueonline.com/",
    features: ["Market Data", "Orders", "Portfolio", "Funds"],
    fields: [
      { key: "userId", label: "User ID", placeholder: "Enter Alice Blue User ID", type: "text", required: true },
      { key: "apiKey", label: "API Key", placeholder: "Enter API Key", type: "password", required: true, helpText: "From Alice Blue ANT Developer Portal" },
    ],
  },
  {
    id: "arrow",
    name: "Arrow",
    logo: "🏹",
    color: "hsl(280 70% 55%)",
    description: "Live NIFTY/BANKNIFTY/FINNIFTY/MIDCPNIFTY/SENSEX option chain via Arrow's instrument master + batched quote API, with Black-Scholes IV/Greeks fill-in.",
    docsUrl: "https://docs.arrow.trade/rest-api/authentication",
    features: ["Option Chain", "Live Quotes", "Batched Multi-Quote", "Black-Scholes Greeks"],
    fields: [
      { key: "appId", label: "App ID", placeholder: "e.g. AR12345", type: "text", required: true, helpText: "From Arrow's Developer Apps section (profile icon -> Trading APIs -> +Create New)." },
      { key: "appSecret", label: "App Secret", placeholder: "App secret", type: "password", required: true, helpText: "Issued alongside App ID when you create the API app. Keep private." },
      { key: "requestToken", label: "Request Token", placeholder: "Paste the request-token from the redirect URL", type: "password", required: true, helpText: "Visit https://app.arrow.trade/app/login?appID=<App ID>, log in (password+TOTP), then copy the 'request-token' query param from the URL you're redirected to. Single-use and short-lived — the server exchanges it once for a 24h session token; when that expires, repeat this step and paste a fresh one." },
    ],
  },
  {
    id: "compositedge",
    name: "Composite Edge (XTS)",
    logo: "🧩",
    color: "hsl(190 80% 45%)",
    description: "Instrument-master + batched-quote option chain for NIFTY, BANKNIFTY, FINNIFTY, MIDCPNIFTY and SENSEX via Composite Edge's XTS market-data API, with Black-Scholes-derived IV/Greeks.",
    docsUrl: "https://xtsapi.compositedge.com/",
    features: ["Option Chain", "Live Quotes", "OI Data", "Expiry List"],
    fields: [
      { key: "apiKey", label: "Market Data App Key", placeholder: "e.g. 3f8a9c2b1e...", type: "text", required: true, helpText: "The App Key issued for the Market Data (XTS) app on your CompositEdge developer account — request API access from Symphony Fintech/CompositEdge support if you don't have one yet." },
      { key: "apiSecret", label: "Market Data Secret Key", placeholder: "Secret key for the Market Data app", type: "password", required: true, helpText: "The Secret Key paired with the Market Data App Key above. Used only for read-only quotes/option-chain data, never stored beyond your session." },
    ],
  },
  {
    id: "definedge",
    name: "Definedge Securities (INTEGRATE)",
    logo: "📊",
    color: "hsl(160 70% 40%)",
    description: "Live NIFTY/BANKNIFTY/FINNIFTY/MIDCPNIFTY/SENSEX option chains from Definedge's INTEGRATE API via daily instrument-master + per-strike quotes, with history-based OI backfill and Black-Scholes IV/Greeks.",
    docsUrl: "https://www.definedgesecurities.com/api-documentation/",
    features: ["Option Chain", "Live Quotes", "OI Backfill", "Multi-Expiry", "Black-Scholes Greeks"],
    fields: [
      { key: "apiToken", label: "API Token", placeholder: "e.g. AB123456", type: "text", required: true, helpText: "From MyAccount → Account → API Config at myaccount.definedgesecurities.com." },
      { key: "apiSecret", label: "API Secret", placeholder: "your api_secret", type: "password", required: true, helpText: "From the same API Config page. Only used by you to complete the 2-step OTP login externally — never sent by this app." },
      { key: "apiSessionKey", label: "API Session Key", placeholder: "paste api_session_key here", type: "password", required: true, helpText: "Definedge login needs a real OTP sent to your phone/email each time, so this app can't log in for you. Complete the 2-step login yourself (Step 1: GET .../login/{api_token} with header api_secret; Step 2: POST .../token with the OTP) and paste the resulting api_session_key here. Lifetime isn't publicly documented — re-paste a fresh one if requests start failing with 401." },
    ],
  },
  {
    id: "firstock",
    name: "Firstock",
    logo: "🥇",
    color: "hsl(45 90% 50%)",
    description: "TOTP-authenticated Firstock integration building live NIFTY/BANKNIFTY/FINNIFTY/MIDCPNIFTY/SENSEX option chains from the daily NFO/BFO symbol master plus batched quote calls, with Black-Scholes-derived IV/Greeks.",
    docsUrl: "https://firstock.in/",
    features: ["Option Chain", "Live Quotes", "TOTP Login", "Open Interest"],
    fields: [
      { key: "userId", label: "User ID", placeholder: "Enter Firstock login/client ID", type: "text", required: true, helpText: "Your Firstock trading login ID" },
      { key: "password", label: "Password", placeholder: "Enter Firstock account password", type: "password", required: true },
      { key: "totpSecret", label: "TOTP Secret", placeholder: "Enter TOTP secret for 2FA", type: "password", required: true, helpText: "Base32 2FA secret from your authenticator app setup — used to auto-generate login codes" },
      { key: "vendorCode", label: "Vendor Code", placeholder: "Enter Firstock Vendor Code", type: "text", required: true, helpText: "Issued when Firstock API access is enabled on your account" },
      { key: "apiKey", label: "API Key", placeholder: "Enter Firstock API Key", type: "password", required: true, helpText: "Issued alongside your Vendor Code for API access" },
    ],
  },
];
