/**
 * Broker catalogue, part 3 of 3 — see brokerCatalogPart1.ts for context.
 */

import type { BrokerInfo } from "./brokerCatalogTypes";

export const BROKERS_PART3: BrokerInfo[] = [
  {
    id: "mstock",
    name: "mStock (Mirae Asset)",
    logo: "🟢",
    color: "hsl(130 55% 40%)",
    description: "Angel One-style TOTP session login with instrument-master + batched-quote option chain, Black-Scholes IV/Greeks via X API.",
    docsUrl: "https://tradingapi.mstock.com/docs/v1/typeB/",
    features: ["Option Chain", "Live Quotes", "TOTP Login", "Orders"],
    fields: [
      { key: "clientId", label: "Client ID / UCC", placeholder: "Enter mStock Client ID", type: "text", required: true, helpText: "Your mStock trading account Client ID (UCC)" },
      { key: "apiKey", label: "API Key", placeholder: "Enter mStock API Key", type: "text", required: true, helpText: "Generated at mstock.com/trading-api — valid ~1 year, sent as the X-PrivateKey header" },
      { key: "password", label: "Password", placeholder: "Enter mStock login password", type: "password", required: true },
      { key: "totpSecret", label: "TOTP Secret", placeholder: "Enter TOTP secret for 2FA", type: "password", required: true, helpText: "Base32 secret from your authenticator app setup — used to auto-generate the 6-digit TOTP code each session (session valid ~12 hours or until midnight IST, whichever is first)" },
    ],
  },
  {
    id: "nubra",
    name: "Nuvama Nubra",
    logo: "🟣",
    color: "hsl(265 60% 55%)",
    description: "TOTP-authenticated live NIFTY/BANKNIFTY/FINNIFTY/MIDCPNIFTY/SENSEX option chain via Nubra's native REST V3 option-chain endpoint, with Black-Scholes IV fill-in where the broker returns null.",
    docsUrl: "https://github.com/marketcalls/broker-api-docs/tree/main/nubra-api-docs",
    features: ["Option Chain", "Live Quotes", "Greeks (native + BS fallback)", "Expiry List"],
    fields: [
      { key: "phone", label: "Registered Mobile Number", placeholder: "9876543210", type: "text", required: true, helpText: "The 10-digit mobile number registered with your Nubra account." },
      { key: "mpin", label: "MPIN", placeholder: "1234", type: "password", required: true, helpText: "Your Nubra login MPIN — used at the /verifypin step of every login." },
      { key: "totpSecret", label: "TOTP Secret", placeholder: "Base32 secret from Nubra's Authenticator setup", type: "password", required: true, helpText: "Enable TOTP once in the Nubra app/web (Settings -> TOTP) and paste the base32 secret it gives you here -- not a 6-digit code, the secret itself." },
    ],
  },
  {
    id: "paytm",
    name: "Paytm Money",
    logo: "💙",
    color: "hsl(205 90% 50%)",
    description: "Live NIFTY/BANKNIFTY/FINNIFTY/MIDCPNIFTY option chain via Paytm Money's native /fno/v1/option-chain endpoint, with a SENSEX-specific instrument-master + batched-quotes fallback.",
    docsUrl: "https://developer.paytmmoney.com/",
    features: ["Option Chain", "Live Quotes", "OI/OI-Change", "Black-Scholes Greeks"],
    fields: [
      { key: "apiKey", label: "API Key", placeholder: "Enter Paytm Money API Key", type: "text", required: true, helpText: "From developer.paytmmoney.com → My Apps" },
      { key: "apiSecret", label: "API Secret", placeholder: "Enter Paytm Money API Secret", type: "password", required: true, helpText: "Paytm calls this api_secret_key — from developer.paytmmoney.com → My Apps" },
      { key: "accessToken", label: "Access Token", placeholder: "Enter access_token from the login flow", type: "password", required: true, helpText: "Complete the login redirect at login.paytmmoney.com, then exchange the request_token for an access_token at POST /accounts/v2/gettoken. Paste the plain access_token here (NOT public_access_token or read_access_token)." },
    ],
  },
  {
    id: "pocketful",
    name: "Pocketful",
    logo: "👛",
    color: "hsl(30 80% 50%)",
    description: "Live NIFTY/BANKNIFTY/FINNIFTY/MIDCPNIFTY/SENSEX option chain via Pocketful's authenticated WebSocket feed, with strikes resolved from its daily contract-master download.",
    docsUrl: "https://api.pocketful.in/docs/",
    features: ["Option Chain", "Live Quotes", "OI", "Greeks (computed)"],
    fields: [
      { key: "accessToken", label: "Access Token", placeholder: "Paste your Pocketful OAuth2 access_token", type: "password", required: true, helpText: "Pocketful uses a full OAuth2 authorization-code flow (browser consent + client_secret exchange). Complete that flow once outside this app (Pocketful's developer console / Postman) and paste the resulting access_token here — same pattern as this app's Upstox/Fyers integrations." },
    ],
  },
  {
    id: "rmoney",
    name: "RMoney (XTS Market Data API)",
    logo: "💵",
    color: "hsl(45 85% 48%)",
    description: "Real-time NIFTY/BANKNIFTY/FINNIFTY/MIDCPNIFTY/SENSEX option chain data via RMoney's Symphony Fintech XTS Market Data API, built from the daily instrument master and batched quote calls with Black-Scholes IV/Greeks.",
    docsUrl: "https://github.com/marketcalls/openalgo/tree/main/broker/rmoney",
    features: ["Option Chain", "Live Quotes", "Open Interest", "Black-Scholes Greeks"],
    fields: [
      { key: "apiKey", label: "Market Data API Key", placeholder: "RMoney Market Data App Key", type: "text", required: true, helpText: "The App Key issued for RMoney's XTS Market Data API (a separate key from the Interactive/trading API)." },
      { key: "apiSecret", label: "Market Data Secret Key", placeholder: "RMoney Market Data Secret Key", type: "password", required: true, helpText: "The Secret Key paired with the Market Data App Key above." },
    ],
  },
  {
    id: "samco",
    name: "SAMCO Securities (StockNote)",
    logo: "🟠",
    color: "hsl(20 85% 52%)",
    description: "Live NIFTY/BANKNIFTY/FINNIFTY/MIDCPNIFTY/SENSEX option chains via SAMCO's StockNote Trade API v3.2, built from its public scrip master and batched multi-quote calls.",
    docsUrl: "https://tradeapi.samco.in/app/login",
    features: ["Option Chain", "Live Quotes", "Index Spot", "Multi-Expiry"],
    fields: [
      { key: "apiKey", label: "API Key", placeholder: "OAuth app API key", type: "text", required: true, helpText: "From the OAuth app you create in the Samco StockNote developer dashboard at tradeapi.samco.in/app/login." },
      { key: "apiSecret", label: "API Secret", placeholder: "OAuth app API secret", type: "password", required: true, helpText: "Shown once when the OAuth app is created — regenerate it from the dashboard if you've lost it. The server exchanges this + the API key for a session token itself; you never need to paste a token." },
    ],
  },
  {
    id: "shoonya",
    name: "Shoonya (Finvasia)",
    logo: "🆓",
    color: "hsl(170 65% 42%)",
    description: "OAuth-authenticated NSE/BSE option chain data via Shoonya's Noren-OMS API, built from a daily instrument master and batched per-contract quotes with Black-Scholes IV/Greeks fill-in.",
    docsUrl: "https://shoonya.com/api-documentation",
    features: ["Option Chain", "Live Quotes", "OI", "5 Indices (incl. SENSEX)"],
    fields: [
      { key: "userId", label: "Trading User ID (UID)", placeholder: "FA12345", type: "text", required: true, helpText: "Your Shoonya trading login ID — sent as `uid` on every API call." },
      { key: "apiKey", label: "API Client ID", placeholder: "e.g. your app's OAuth client_id", type: "text", required: true, helpText: "The client_id issued when you registered an app on Shoonya's developer console." },
      { key: "apiSecret", label: "API Secret Key", placeholder: "App secret key", type: "password", required: true, helpText: "The app secret paired with your API Client ID — used only to compute the login checksum, never sent as-is." },
      { key: "requestCode", label: "Authorization Code", placeholder: "One-time code from the OAuth redirect", type: "password", required: true, helpText: "Visit https://api.shoonya.com/OAuthlogin/authorize/oauth?client_id=<API Client ID>, log in, and paste the `code` param from the redirect URL here. Expires within minutes — regenerate if login fails." },
    ],
  },
  {
    id: "tradejini",
    name: "Tradejini (CubePlus)",
    logo: "🧞",
    color: "hsl(255 65% 55%)",
    description: "Live NIFTY/BANKNIFTY/FINNIFTY/MIDCPNIFTY/SENSEX option-chain data via Tradejini's persistent NxtradStream feed, including broker-computed IV and Greeks.",
    docsUrl: "https://developer.tradejini.com/",
    features: ["Option Chain", "Live Quotes", "Server-side Greeks/IV", "Auto TOTP Login"],
    fields: [
      { key: "apiKey", label: "API Key", placeholder: "Enter Tradejini App API Key", type: "text", required: true, helpText: "From the Tradejini developer portal (app registration) — the app's static IP must be whitelisted there for login to succeed" },
      { key: "password", label: "CubePlus PIN", placeholder: "Enter your CubePlus login PIN", type: "password", required: true, helpText: "Your CubePlus trading-app login PIN, not your account password" },
      { key: "totpSecret", label: "TOTP Secret", placeholder: "Enter TOTP secret for 2FA", type: "password", required: true, helpText: "Base32 secret from Tradejini's TOTP/2FA setup — used to auto-generate a fresh login code every session" },
    ],
  },
  {
    id: "tradesmart",
    name: "TradeSmart (Noren v2)",
    logo: "📈",
    color: "hsl(195 70% 45%)",
    description: "Live NIFTY/BANKNIFTY/FINNIFTY/SENSEX option chain data via TradeSmart's Noren v2 API, built from its daily instrument master and rate-limited quote calls.",
    docsUrl: "https://apidocs.tradesmartonline.in/v2/",
    features: ["Option Chain", "Live Quotes", "OI & Volume", "Multi-Expiry"],
    fields: [
      { key: "clientId", label: "Client ID", placeholder: "AB1234", type: "text", required: true, helpText: "Your TradeSmart trading Client ID / UCC." },
      { key: "apiKey", label: "App Key", placeholder: "App key from your TradeSmart API app", type: "text", required: true, helpText: "From your registered TradeSmart API application." },
      { key: "apiSecret", label: "Secret Key", placeholder: "Secret key from your TradeSmart API app", type: "password", required: true },
      { key: "requestCode", label: "Authorization Code", placeholder: "One-time code from the OAuth redirect", type: "password", required: true, helpText: "Open https://v2api.tradesmartonline.in/OAuthlogin/authorize/oauth?client_id=<App Key>, log in, and paste the 'code' param from the redirect URL here. It is single-use and expires within minutes — generate a fresh one each session." },
    ],
  },
  {
    id: "wisdom",
    name: "Wisdom Capital (XTS)",
    logo: "🦉",
    color: "hsl(275 55% 50%)",
    description: "Live NIFTY/BANKNIFTY/FINNIFTY/MIDCPNIFTY/SENSEX option chains via Wisdom Capital's XTS market-data API, with Black-Scholes IV/Greeks fill-in.",
    docsUrl: "https://developers.symphonyfintech.in/doc/marketdata/",
    features: ["Option Chain", "Live Quotes", "Open Interest", "Expiry List"],
    fields: [
      { key: "apiKey", label: "Market Data App Key", placeholder: "Your Wisdom Capital market-data appKey", type: "text", required: true, helpText: "From Wisdom Capital's XTS developer portal — the market-data (not interactive/trading) app key." },
      { key: "apiSecret", label: "Market Data Secret Key", placeholder: "Your Wisdom Capital market-data secretKey", type: "password", required: true, helpText: "Paired secret for the market-data app key above. Never logged; used only to log in and fetch a session token server-side." },
    ],
  },
  {
    id: "zebu",
    name: "Zebu (Mynt)",
    logo: "🦓",
    color: "hsl(0 0% 40%)",
    description: "Live NIFTY/BANKNIFTY/FINNIFTY/MIDCPNIFTY/SENSEX option chains via Zebu's Noren-based Mynt API, with Black-Scholes-filled Greeks.",
    docsUrl: "https://docs.openalgo.in/connect-brokers/brokers/zebu",
    features: ["Option Chain", "Live Quotes", "OAuth Login", "OI Data"],
    fields: [
      { key: "userId", label: "Trading User ID", placeholder: "e.g. Z56004", type: "text", required: true, helpText: "Your Zebu MYNT login / trading user ID. Sent as uid/actid on every API call." },
      { key: "clientId", label: "OAuth Client ID", placeholder: "e.g. Z56004_U", type: "text", required: true, helpText: "From mynt.zebuetrade.com: Profile > Settings > OAuth Key screen." },
      { key: "apiSecret", label: "OAuth Secret Code", placeholder: "Paste your Secret Code", type: "password", required: true, helpText: "Generated alongside the Client ID on the same OAuth Key screen. Never shared." },
      { key: "authCode", label: "Authorization Code", placeholder: "Paste the one-time code from the redirect URL", type: "text", required: true, helpText: "Visit go.mynt.in/OAuthlogin/authorize/oauth?client_id=<clientId>, log in, and copy the ?code= from the redirect. Single-use, expires within minutes — you'll need a fresh one whenever the session expires." },
    ],
  },
];
