import { useEffect, useState } from "react";
import { Check, Copy } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { StrategyLeg } from "@/lib/mockData";

interface Stats {
  maxProfitUnlimited: boolean;
  maxLossUnlimited: boolean;
  maxProfit: number;
  maxLoss: number;
  riskReward: string;
  probOfProfit: number;
  netPremium: number;
  breakevens: number[];
  totalDelta: number;
  totalGamma: number;
  totalTheta: number;
  totalVega: number;
}

interface Props {
  legs: StrategyLeg[];
  stats: Stats;
  spotPrice: number;
  lotSize: number;
  selectedPreset: string;
}

/** Copies StrategyBuilder's current trade plan as plain text — extracted
 * from StrategyBuilder.tsx to keep that page under the repo's 300-line law. */
export function CopyTradeButton({ legs, stats, spotPrice, lotSize, selectedPreset }: Props) {
  const [copied, setCopied] = useState(false);

  // Reset the "Copied!" state via an effect with cleanup rather than a bare
  // setTimeout in the click handler, so the timer doesn't leak/fire a state
  // update if the component unmounts (e.g. user navigates away) mid-countdown.
  useEffect(() => {
    if (!copied) return;
    const t = setTimeout(() => setCopied(false), 2000);
    return () => clearTimeout(t);
  }, [copied]);

  const handleCopy = () => {
    const lines = [
      `📊 ${selectedPreset || "Custom Strategy"} — Trade Plan`,
      `${"─".repeat(40)}`,
      `Spot: ₹${spotPrice.toLocaleString("en-IN")} | Lot Size: ${lotSize}`,
      ``,
      ...legs.map((l, i) => `  Leg ${i + 1}: ${l.action} ${l.type} ${l.strike} × ${l.lots} lots @ ₹${l.premium}`),
      ``,
      `Max Profit: ${stats.maxProfitUnlimited ? "Unlimited" : `₹${stats.maxProfit.toLocaleString("en-IN")}`}`,
      `Max Loss:   ${stats.maxLossUnlimited ? "Unlimited" : `₹${stats.maxLoss.toLocaleString("en-IN")}`}`,
      `R:R Ratio:  ${stats.riskReward}`,
      `Prob Profit: ${stats.probOfProfit}%`,
      `Net Premium: ${stats.netPremium >= 0 ? "Credit" : "Debit"} ₹${Math.abs(stats.netPremium).toLocaleString("en-IN")}`,
      `Breakevens:  ${stats.breakevens.length > 0 ? stats.breakevens.map((b: number) => b.toLocaleString("en-IN")).join(", ") : "None"}`,
      ``,
      `Greeks: Δ${stats.totalDelta} | Γ${stats.totalGamma} | Θ${stats.totalTheta} | ν${stats.totalVega}`,
      `${"─".repeat(40)}`,
      `Generated by Mr. Chartist Options Terminal`,
    ];
    navigator.clipboard.writeText(lines.join("\n"));
    setCopied(true);
  };

  return (
    <Button variant="outline" size="sm" className="h-7 gap-1.5 text-xs" onClick={handleCopy}>
      {copied ? <Check className="h-3 w-3 text-bullish" /> : <Copy className="h-3 w-3" />}
      {copied ? "Copied!" : "Export"}
    </Button>
  );
}
